# Generated by Django 4.1.6 on 2023-02-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='illness',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='report_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicinereport',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptoms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
