# Generated by Django 4.1.6 on 2023-05-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_patient_address_remove_patient_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='illness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.illness'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicinereport',
            name='report_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptoms',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='drugs',
            field=models.ManyToManyField(to='health.drugs'),
        ),
    ]
