# Generated by Django 4.1.6 on 2023-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_drugs_treatment_illness_alter_illness_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicinereport',
            name='report_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptoms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
