# Generated by Django 4.1.6 on 2023-06-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_drugs_description_alter_drugs_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=10000)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.illness')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='medicine_reports/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.illness')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicinereport',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='date_reported',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='drugs',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='degree',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptoms',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Drugs',
        ),
        migrations.DeleteModel(
            name='MedicineReport',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.patients'),
        ),
        migrations.AddField(
            model_name='illnesstreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.treatment'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='pills',
            field=models.ManyToManyField(to='health.pills'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_types',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='health.treatmenttypes'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patients'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='illness',
            field=models.ManyToManyField(through='health.IllnessTreatment', to='health.illness'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ManyToManyField(to='health.patients'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
